packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@rolldown/binding-openharmony-arm64@1.2.8'
